SET PATH=.;..;C:\DOS-AS~1\MASM611\BIN;C:\DOS-AS~1\MASM611\BINR;C:\DOS-AS~1\SAMPLES;%PATH%
SET INCLUDE=C:\DOS-AS~1\MASM611\INCLUDE
SET HELPFILES=C:\DOS-AS~1\MASM611\HELP\*.HLP
SET TMP=C:\DOS-AS~1\TEMP
